# Model Arguments
model:
  model_path: "./checkpoints/models/7b/"
  tokenizer_path: "./checkpoints/tokenizer/text_tokenizer.json"
  vqgan_config_path: "./checkpoints/tokenizer/vqgan.yaml"
  vqgan_ckpt_path: "./checkpoints/tokenizer/vqgan.ckpt"

# Environment
device: cuda
dtype: bf16
seed: 217


# LLM Eval specific eval args
model_name: chameleon
tasks: 
  - realworldqa
  - llava_bench_coco
  - mmmu

limit: null
max_seq_length: 4096

mm_eval_args:
  output_path: ./logs/
